services:
  docs:
    image: doko_backend_local_docs
    container_name: doko_backend_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./doko_backend:/app/doko_backend:z
    ports:
      - '9000:9000'
    command: /start-docs
